### ISSUE TITLE
Cannot change theme

### ISSUE THREAD

**Issue by DSDeniso** [radera/victory#39]
CSS exists for both light and dark themes, but there no setting to change between them.

Maybe the theme should depend on whether it's day at the users location, with a notification telling the user that the relevant theme has been applied and a button to change it back.

"It's day outside, so we changed the look to something more appropriate. >Switch back to dark theme<"

**Comment by Melonendk** [comment]
It is now made to u can just switch in the settings and it permanent until the user change it by themselves
