### ISSUE TITLE
Duplicate CSS across themes

### ISSUE THREAD

**Issue by DSDeniso** [radera/victory#40]
light.css and dark.css contains some of the same properties. These common properties should be moved to a CSS that's used regardless of the theme. The theme CSS-files should only change what's relevant to the theme and not have to do general stuff like making profile pictures round.

**Comment by johncoffee** [comment]
Julian syns: Light.css er default, og dark.css overwriter - i stedet for at bytte den ene ud med den anden.

**Comment by Melonendk** [comment]
Så meget som det nu ville give mening og gøre det er det kun en midlertidig løsning da hele frontend er ved at blive lavet om. Samt så vil det ikke bare kun være så det er dark og light der vil være så den vil ændre hele looked :)
