### ISSUE TITLE
No app icon

### ISSUE THREAD

**Issue by DSDeniso** [radera/victory#43]
We need an app icon for when the application is added to the home screen.

**Comment by Melonendk** [comment]
easy to add basicly just a line in the header and It is basicly working for Android

**Comment by DSDeniso** [comment]
Same for iOS, but would you be able to make the icon itself?

**Comment by Melonendk** [comment]
Its just and icon its basicly just copy paste the things right now :)

**Comment by DSDeniso** [comment]
Awesome. I'm just not used to doing it, so you're basically 1000 times faster.

**Comment by Melonendk** [comment]
Should be fixed now cannot text because it takes time before the browser sees the icons and cache them
